#pragma once

#include <vector>
#include <string>

enum SCRIPT_TYPE
{
	ATTACKSPRITESCRIPT,
	BREAKABLEFLOORSCRIPT,
	CAMERAMOVESCRIPT,
	CAMERASCRIPT,
	CURSORSCRIPT,
	DOORSCRIPT,
	EFFECTSCRIPT,
	ENEMYDETECTORSCRIPT,
	ENEMYGANGSTERSCRIPT,
	ENEMYGRUNTSCRIPT,
	ENEMYSCRIPT,
	FANSCRIPT,
	GAMEMANAGERSCRIPT,
	GANGSTERBULLETSCRIPT,
	GROUNDSCRIPT,
	GRUNTATTACKSPRITESCRIPT,
	HUDSCRIPT,
	LASERSCRIPT,
	LASERSWITCHSCRIPT,
	LIGHTFLICKERSCRIPT,
	MISSILESCRIPT,
	MONSTERSCRIPT,
	ONEWAYPLATFORMSCRIPT,
	PLAYERSCRIPT,
	RAMPSCRIPT,
	TITLESCRIPT,
	WALLSCRIPT,
	END,
};

using namespace std;

class CScript;

class CScriptManager
{
public:
	static void GetScriptInfo(vector<wstring>& _vec);
	static CScript * GetScript(const wstring& _strScriptName);
	static CScript * GetScript(UINT _iScriptType);
	static const wchar_t * GetScriptName(CScript * _pScript);
};
